### ISSUE TITLE
友链申请

### ISSUE THREAD

**Issue by dpkg123** [FikaNeko/FikaNeko.github.io#1]
name: dokg123
link: https://dpkg123.site
avatar: https://dpkg123.site/favicon.jpg
descr: 书山有路勤为径，学海无涯苦作舟。

**Comment by FikaNeko** [comment]
> name: dokg123 link: https://dpkg123.site avatar: https://dpkg123.site/favicon.jpg descr: 书山有路勤为径，学海无涯苦作舟。

已添加，感谢支持
