### ISSUE TITLE
求友链wwww

### ISSUE THREAD

**Issue by ivansnow02** [FikaNeko/FikaNeko.github.io#2]
name: Snow' s Blog
link: https://ivansnow02.github.io/about/
avatar: https://ivansnow02.github.io/img/avatar.png
descr: Code Blog

**Comment by FikaNeko** [comment]
> name: Snow' s Blog link: https://ivansnow02.github.io/about/ avatar: https://ivansnow02.github.io/img/avatar.png descr: Code Blog

已添加，感谢支持
