### ISSUE TITLE
换个友链~

### ISSUE THREAD

**Issue by NiuBoss123** [FikaNeko/FikaNeko.github.io#3]
~~可以在这发就不上博客评论区发了~~

---
name: 御坂秋生
link: https://www.akio.top
avatar: https://server.akio.top/icon
descr: 不努力就只能听到别人的好消息

**Comment by FikaNeko** [comment]
> ~~可以在这发就不上博客评论区发了~~
> 
> ---
> name: 御坂秋生
> link: https://www.akio.top
> avatar: https://server.akio.top/icon
> descr: 不努力就只能听到别人的好消息

非常抱歉，需要高考后再添加友链，目前暂无电脑><
感谢支持

**Comment by FikaNeko** [comment]
> ~~可以在这发就不上博客评论区发了~~
> 
> ---
> name: 御坂秋生
> link: https://www.akio.top
> avatar: https://server.akio.top/icon
> descr: 不努力就只能听到别人的好消息

Addition:当您注意到issue closed表明已经成功添加友链

**Comment by FikaNeko** [comment]
> ~可以在这发就不上博客评论区发了~
> 
> name: 御坂秋生 link: https://www.akio.top avatar: https://server.akio.top/icon descr: 不努力就只能听到别人的好消息

已添加，感谢支持
