### ISSUE TITLE
友链申请

### ISSUE THREAD

**Issue by ghost** [FikaNeko/FikaNeko.github.io#4]
name: SkyHigh  
link: https://skyhigh.moe  
avatar: https://mypic.skyhigh.moe/pic/logo/avatar-0.jpg  
descr: SkyHigh'Site

**Comment by FikaNeko** [comment]
已添加，但头像貌似不能正确获取，请检查链接

**Comment by ghost** [comment]
> 已添加，但头像貌似不能正确获取，请检查链接

已更新，见 #5   
忘记添加cf防盗链白名单了(￣▽￣)"

**Comment by FikaNeko** [comment]
已合并pull request
